<?php
return [
	"dirProjeto"=>"/var/www/pingpongs/",
	"tpAmb"=>2,
	"pathXmlUrlFileNFe"=>"{dirProjeto}arquivos/config/nfe_ws3_mod55.xml",
	"pathXmlUrlFileCTe"=>"{dirProjeto}arquivos/config/cte_ws2.xml",
	"pathXmlUrlFileMDFe"=>"{dirProjeto}arquivos/config/mdfe_ws1.xml",
	"pathXmlUrlFileCLe"=>"",
	"pathXmlUrlFileNFSe"=>"",
	"pathNFeFiles"=>"",
	"pathCTeFiles"=>"",
	"pathMDFeFiles"=>"",
	"pathCLeFiles"=>"",
	"pathNFSeFiles"=>"",
	"pathCertsFiles"=>"{dirProjeto}arquivos/certs/",
	"siteUrl"=>"",
	"schemesNFe"=>"PL_008f",
	"schemesCTe"=>"PL_CTe_200",
	"schemesMDFe"=>"PL_MDFe_100",
	"schemesCLe"=>"",
	"schemesNFSe"=>"",
	"aDocFormat"=>[
		"format"=>"L",
		"paper"=>"A4",
		"southpaw"=>"1",
		"pathLogoFile"=>"",
		"logoPosition"=>"L",
		"font"=>"Times",
		"printer"=>""
	],
	"aMailConf"=>[
		"mailAuth"=>"1",
		"mailFrom"=>false,
		"mailSmtp"=>"",
		"mailUser"=>"",
		"mailPass"=>"",
		"mailProtocol"=>"",
		"mailPort"=>"",
		"mailFromMail"=>null,
		"mailFromName"=>null,
		"mailReplayToMail"=>null,
		"mailReplayToName"=>null,
		"mailImapHost"=>null,
		"mailImapPort"=>null,
		"mailImapSecurity"=>null,
		"mailImapNocerts"=>null,
		"mailImapBox"=>null
	],
	"aProxyConf"=>[
		"proxyIp"=>"",
		"proxyPort"=>"",
		"proxyUser"=>"",
		"proxyPass"=>""
	]
];
?>